### PR TITLE
Added ZorinOS logo

### PR DESCRIPTION
**Pull request by Kevadroz**

### CODE REVIEW

**Review by Epikest — APPROVED** [review]
discussed in discord thread

**Comment by Kevadroz** [comment]
All the mockups:
ZorinOS
ZorinOS2
ZorinOS3
ZorinOS4
ZorinOS5
ZorinOS6
ZorinOS7

**Comment by ryleu** [comment]
are we ready to merge this?

**Comment by Kevadroz** [comment]
> are we ready to merge this?

I think a poll goes first

**Comment by Kevadroz** [comment]
Closing this since it's being handled externally.

**Pull request closed without merging**
